CONFIGS:
  CSV_PATH: '../data/diabetes.csv'
  
  POLICY: 'mean'
  MODELS: ['mlp', 'rf', 'lr']
  BASELINES: [null, 0.5, 0.7, 0.9]

HYPERPARAMS:
  RANDOM_SEED: 7
  TEST_SIZE: 0.2

FEATURES:
  NUMERICAL: ['BloodPressure', 'BMI', 'Glucose', 'Insulin', 'SkinThickness']
  CATEGORICAL: []
  BINARY: []
  TARGET: ['Outcome']
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']

MODELS:
  USE_ENSEMBLE: false
