CONFIGS:
  CSV_PATH: '../data/healthcare-dataset-stroke-data.csv'
  POLICY: 'mean'
  MODELS: ['lr', 'rf', 'mlp']
  BASELINES: [null, 0.5, 0.3, 0.1]

HYPERPARAMS:
  RANDOM_SEED: 6
  TEST_SIZE: 0.4

FEATURES:
  NUMERICAL: ['age', 'avg_glucose_level', 'bmi']
  BINARY: []
  CATEGORICAL: []
  TARGET: ['stroke']
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']

MODELS:
  USE_ENSEMBLE: true
