CONFIGS:
  DIABS_PATH: '../data/diabetes.csv'
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']
  FEATURES: ['BloodPressure', 'BMI', 'Glucose', 'Insulin', 'SkinThickness']
  POLICY: 'sum'

HYPERPARAMS:
  RANDOM_SEED: 7
  TEST_SIZE: 0.2