MODEL_INFO:
  NAME: "Logistic-Regression-1"
  TYPE: "logistic_regression"
  SOURCE_MODULE: "sklearn"

MODEL_PARAMS:
  ARGUMENTS:
    dual: false
    penalty: l2
    C: 1.0
    class_weight: "balanced"