CONFIGS:
  CSV_PATH: '../data/diabetes.csv'
  POLICY: 'sum'
  MODELS: ['lr', 'rf', 'mlp']
  BASELINES: [1, 0.5, 0.3, 0.1]

HYPERPARAMS:
  RANDOM_SEED: 7
  TEST_SIZE: 0.2

FEATURES:
  NUMERICAL: ['BloodPressure', 'BMI', 'Glucose', 'Insulin', 'SkinThickness']
  CATEGORICAL: []
  BINARY: []
  TARGET: ['Outcome']
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']

MODELS:
  USE_ENSEMBLE: true
  SKIP_MULTIPROCESSING: false
