CONFIGS:
  CSV_PATH: '../data/healthcare-dataset-stroke-data.csv'
  POLICY: 'sum'
  MODELS: ['lr', 'rf', 'mlp']
  BASELINES: [1, 0.5, 0.3, 0.1]

HYPERPARAMS:
  RANDOM_SEED: 6
  TEST_SIZE: 0.4

FEATURES:
  NUMERICAL: ['age', 'avg_glucose_level', 'bmi']
  CATEGORICAL: ['work_type', 'smoking_status']
  BINARY: []
  TARGET: ['stroke']
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']

MODELS:
  USE_ENSEMBLE: true
