CONFIGS:
  CSV_PATH: '../data/healthcare-dataset-stroke-data.csv'
  POLICY: 'mean'
  MODELS: ['lr', 'rf', 'svm', 'mlp']
  BASELINES: [1, 0.5, 0.3, 0.1]

HYPERPARAMS:
  RANDOM_SEED: 6
  TEST_SIZE: 0.4

FEATURES:
  NUMERICAL: ['age', 'avg_glucose_level', 'bmi']
  CATEGORICAL: ['work_type', 'smoking_status']
  BINARY: ['heart_disease']
  TARGET: ['stroke']
  SET_FEATURE_VALUES:
    'avg_glucose_level': 95
    'bmi': 20

MODELS:
  USE_ENSEMBLE: false
  SKIP_MULTIPROCESSING: false
  NUM_MODELS_RANK: 2

